name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall the dependencies
        run: pip3 install --no-cache-dir -r requirements-dev.txt
      - name: Execute the unit tests
        run: pytest tests
  test_pypi_package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Test the package build
        run: python3 .github/workflows/test_pypi_package_build.py
